# Generated by Django 4.2.2 on 2023-08-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babatuoshimingAPI", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materiel",
            name="remark",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
