# Generated by Django 4.2.2 on 2023-08-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("babatuoshimingAPI", "0002_alter_materiel_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="materiel",
            name="merchant",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
