# Generated by Django 4.2.2 on 2023-08-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "babatuoshimingAPI",
            "0004_materiel_available_quantity_materiel_loss_quantity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="status",
            field=models.IntegerField(
                choices=[(0, "禁用"), (1, "教师"), (2, "财务"), (3, "超级管理员")], default=0
            ),
        ),
    ]
